<a href="https://colab.research.google.com/github/rffaiani/semana-datascience-flai/blob/main/Projeto_Album_de_Figurinhas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Bem-vindos ao Projeto do Album de Figurinhas')

Bem-vindos ao Projeto do Album de Figurinhas


#Projeto

##Projeto Album de Figurinhas

#Atribuição de Variáveis

In [3]:
professor = 'Prof. Ricardo Rocha'
live = "youtube canal flai"
sobre = "python para iniciantes"

print(professor, live, sobre)

Prof. Ricardo Rocha youtube canal flai python para iniciantes


In [4]:
type(professor)

str

In [6]:
help(print)
#documentação básica do print

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [7]:
len(professor)
#tamanho - qtde de caracteres

19

In [8]:
a = 2
b = 3

print('Soma', a + b)
print('Subtração', a-b)
print('Multiplicação', a*b)
print('Divisão', a/b)
print('Exponenciação', a**b)


Soma 5
Subtração -1
Multiplicação 6
Divisão 0.6666666666666666
Exponenciação 8


In [13]:
print('Resto da divisão', b%a)
print('Divisão inteira', b//a)

Resto da divisão 1
Divisão inteira 1


In [18]:
True or False


True

In [19]:
True and False

False

In [20]:
not True

False

In [21]:
# Conectivos lógicos

(a == b) or (a < b)

True

In [22]:
a>=b

False

In [23]:
a != b

True

In [24]:
# Booleanos é importante para condicionais.


In [ ]:
#programinha para calcular equação do segundo grau =>  $$ a x^2 + b x + c = 0 $$

#Programinha para calcular equação do segundo grau:

$$ a x^2 + b x + c = 0 $$

In [31]:
a, b, c = 1, 2, -1

delta = b**2 - 4*a*c

if delta > 0:
  x1 = round((-b + delta**(1/2)) / (2*a), 3)
  x2 = round((-b - delta**(1/2)) / (2*a), 3)
  print('As raízes são: {} e {}' .format(x1,x2))
elif delta == 0:
  x = round(-b/(2*a), 3)
else:
  print('A equação não possui raízes reais.')


As raízes são: 0.414 e -2.414


In [32]:
#definição de funções

def Minhafuncao():
  print('***************')
  print('Rafael')

Minhafuncao()

***************
Rafael


In [36]:

def Bhaskara(a,b,c):
  
  delta = b**2 - 4*a*c

  if delta > 0:
    x1 = round((-b + delta**(1/2)) / (2*a), 3)
    x2 = round((-b - delta**(1/2)) / (2*a), 3)
    print('As raízes são: {} e {}' .format(x1,x2))
  elif delta == 0:
    x = round(-b/(2*a), 3)
  else:
    print('A equação não possui raízes reais.')


In [37]:
Bhaskara(a=1,b=2,c=-1)

As raízes são: 0.414 e -2.414


In [41]:
# Listas

lista = ['Rafael', 28, Bhaskara]

In [42]:
lista[1]

28

In [43]:
lista[2]

<function __main__.Bhaskara>

In [44]:
lista[2](a=1,b=2,c=3)

A equação não possui raízes reais.


In [45]:
lista = ['Rafael', 28, Bhaskara, [1,2,3]]

In [46]:
lista[3]

[1, 2, 3]

In [48]:
lista[3][2]

3

In [49]:
lista2 = list('Rafael')

In [50]:
lista2

['R', 'a', 'f', 'a', 'e', 'l']

In [51]:
#pegar tudo até a 2a. posição

lista2[:2]


['R', 'a']

In [52]:
lista2[::2]

['R', 'f', 'e']

#importação de bibliotecas

In [55]:
from math import pi, sqrt

In [54]:
pi


3.141592653589793

In [56]:
sqrt(5)

2.23606797749979

In [59]:
import math as m

In [60]:
m.ceil(2.3)

3

In [61]:
m.floor(2.3)

2

In [ ]:
#teto e chão

#Biblioteca Numpy

In [63]:
import numpy as np

In [64]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [65]:
3 * np.array([1,2,3,4])

array([ 3,  6,  9, 12])

In [67]:
2.2 + np.array([1,2,3,4])

array([3.2, 4.2, 5.2, 6.2])

In [69]:
np.array( [[1,2,3,4] , [5,6,7,8]] )

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
#cria repetição de números
np.arange(10, 30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [73]:
np.arange(10, 30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [74]:
#dado o vetor vai tirar uma amostra com 3 números.

np.random.choice([1,2,3,4,5], size = 3)

array([3, 4, 4])

In [76]:
#album 212 figurinhas
x = np.arange(1, 213)
np.random.choice(x, size = 4) #representando a abertura de 1 pacote com 4 figurinhas.


array([ 93,  50, 113, 174])

In [77]:
#numpy all trata de booleanos (lista de booleanos)
np.all([True, True, True])

True

In [78]:
np.all([True, True, False])

False

In [79]:
#numpy any - se pelo menos 1 for True dá True
np.any([True, False, False])

True

#Iteradores

In [80]:
#FOR

for i in [1,2,3,4,5]:
  print(i**2)

1
4
9
16
25


In [81]:
for i in [1,2,3,4,5]: #5 iterações
  print(np.random.choice(x, size = 4))

[ 71 145 198 109]
[164 114  74 119]
[131 180 134  82]
[147 138 140  72]
[171 198 152 184]


In [83]:
for i in np.arange(0,10): #10 iterações
  print(np.random.choice(x, size = 4))

[111  88 100  22]
[179 205  21 189]
[ 65  51 191 208]
[ 40 116 145 196]
[122  34  53  44]
[201 167  12 120]
[124 201  53 138]
[ 76  49 172  59]
[ 55 129  42 205]
[ 69 181 147 176]


In [85]:
#WHILE

contador = 0
while True:
  contador = contador + 1
  print(contador*2)
  if contador == 10:
    break

2
4
6
8
10
12
14
16
18
20


In [88]:
contador = 0
while contador < 10:
  contador = contador + 1
  print(contador*2)

  if contador == 10:
    break

2
4
6
8
10
12
14
16
18
20


#PROJETO ALBUM DE FIGURINHAS.............................

Total de cromos: 212

Suposições:
1. Todas as figurinhas tem a possibilidade de serem sorteadas.
2. Um pacotinho é comprado por vez até que se complete o albúm.

ALGORITMO:

RESPONDER PERGUNTAS:

In [89]:
n_album = 212
preco_pacote = 4
cromos_pacote = 4
preco_album = 10



In [90]:
album = np.zeros(n_album)
album

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
#comprar 1 pacote

pacotinho = np.random.choice(np.arange(0, n_album), size = 4)

In [101]:
pacotinho

array([  2,  29,   5, 126])

In [102]:
#colar no album

album[pacotinho[0]] += 1
album[pacotinho[1]] += 1
album[pacotinho[2]] += 1
album[pacotinho[3]] += 1

album


array([0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 5., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0.])

In [105]:
not np.all(album>=1) #álbum está incompleto? Sim, verdadeiro.

True

In [ ]:



#PROGRAMA


In [138]:

n_album = 212
preco_pacote = 4
cromos_pacote = 4
preco_album = 10


def Simula():

  album = np.zeros(n_album)
  pacotes = 0

  while True:
      pacotinho = np.random.choice(np.arange(0, n_album), size = 4)

      pacotes += 1

      for i in [0,1,2,3]:
        album[pacotinho[i]] += 1

      if np.all(album >=1):
        break
    
  custo = pacotes*preco_pacote + preco_album
  return custo




In [139]:
Simula()

1722

In [140]:
#pra saber o valor médio, replicar a simulação algumas vezes e depois tirar o valor médio.



In [145]:
s= 10

resultados = []

for i in range(s):
  pessoa = Simula()
  resultados.append(pessoa)

resultados


#sim = np.array(resultados).mean()



[1290, 1462, 1554, 1122, 1094, 902, 926, 982, 1378, 1062]

In [147]:
media = np.array(resultados).mean()
media

1177.2

In [ ]:
#acima valor médio para 10 amostras.

In [ ]:
#ok